name: First task workflow

on: push

jobs:      
    
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Set up Node version
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: Install Dependencies
        run: npm ci
      - name: Lint testing
        run: npm run lint
      - name: Unit testing
        run: npm run test
    
  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Set up Node version
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Set up Node version
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: Install Dependencies
        run: npm ci
      - name: Deploy project
        run: echo "Deploying ..."