name: First task workflow

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Set up Node version
        uses: actions/setup-node@v4
        with: 
          node-version: '23.9.0'
      - name: Install Dependencies
        run: npm ci
      - name: Lint Code
        run: npm run lint

    
    # test:
    
    # build:

    # deploy: