name: Event Details

on: 
  issues:
    types: [opened, closed]

jobs:
  event_info:
    runs-on: ubuntu-latest
    steps:
      - name: Get Info About Event
        run: echo "${{toJson(github.event.issue)}}"